---
- name: Create tower Job Template
tower_job_template:
  tower_host: "{{ tower.host }}"
  tower_password: "{{ tower.password }}"
  tower_username: "{{ tower.username }}"
  name: "{{ job_template.name }}"
  description: "{{ job_template.description | default(default_template_description, true) }}"
  job_type: "{{ job_template.job_type }}"
  ask_job_type: "{{ job_template.ask_job_type | default(omit) }}"
  inventory: "{{ job_template.inventory | default(default_inventory, true) }}"
  ask_inventory: "{{ job_template.ask_inventory | default(omit) }}"
  project: "{{ job_template.project }}"
  playbook: "{{ job_template.playbook }}"
  credential: "{{ job_template.credential }}"
  ask_credential: "{{ job_template.ask_credential | default(omit) }}"
  machine_credential: "{{ job_template.machine_credential | default(omit) }}"
  network_credential: "{{ job_template.network_credential | default(omit) }}"
  job_tags: "{{ job_template.job_tags | default(omit) }}"
  ask_tags: "{{ job_template.ask_tags | default(omit) }}"
  skip_tags: "{{ job_template.skip_tags | default(omit) }}"
  become_enabled: "{{ job_template.become_enabled | default(omit) }}"
  cloud_credential: "{{ job_template.cloud_credential | default(omit) }}"
  forks: "{{ job_template.forks | default(omit) }}"
  host_config_key: "{{ job_template.host_config_key | default(omit) }}"
  limit: "{{ job_template.limit | default(omit) }}"
  verbosity: "{{ job_template.verbosity | default(omit) }}"
  state: "{{ job_template.state | default(omit) }}"
loop: "{{ job_templates }}"
loop_control:
  loop_var: job_template

- name: Configure and Tag Job_Template to Default Team's account with permission privilege
  tower_role:
    tower_host: "{{ tower.host }}"
    tower_password: "{{ tower.password }}"
    tower_username: "{{ tower.username }}"
    job_template: "{{ tower_role_job_template.0.name }}"
    state: "{{ tower_role_job_template.0.state | default(omit) }}"
    team: "{{ tower_role_job_template.1.name }}"
    role: "{{ tower_role_job_template.1.permission }}"
    with_nested: 
      - "{{ job_templates }}"
      - "{{ default_teams }}"
  loop_control:
    loop_var: tower_role_job_template