---
- name: "tower: load"
  include_vars:
    file: "config/tower.yaml"

- name: "tower_credentials: load"
  include_vars:
    file: "config/credentials.yaml"

- name: "tower_credentials: configure"
  import_role:
    name: tower_credentials
    tasks_from: configure_credentials