---
- name: "job_templates: load"
  include_vars:
    file: "config/job_templates.yaml"

- name: "job_templates: configure"
  import_role:
    name: tower_job_templates
    tasks_from: configure_job_templates