---
inventories:
  name: Network_Inventory
  description: This is description
  organization: Default
  variables:
    ansible_python_interpreter: python
    ansible_connection: network_cli
  groups:
    - name: eos
      variables:
        ansible_network_os: eos
        ansible_become: yes
        ansible_become_method: enable
        ansible_network_provider: ansible-network.arista_eos

    - name: ios
      variables:
        ansible_network_os: ios
        ansible_become: yes
        ansible_become_method: enable
        ansible_network_provider: ansible-network.cisco_ios
