---
projects:
  #- name: "Ansible Network"
  -  local_path: test_configurator
  #  description: This is test description for IOS credential
  #  organization: Default
  #  kind: ssh
  #  username: admin_new
  #  password: test123
  #  state: present
