---
- name: Create Inventory
  tower_inventory:
    tower_host: "{{ tower.host | default(default_tower_host, true) }}"
    tower_password: "{{ tower.password | default(default_tower_password, true) }}"
    tower_username: "{{ tower.username | default(default_tower_username, true) }}"
    name: "{{ inventory.name | default(default_inventory) }}"
    organization: "{{ inventory.organization | default(default_organization, true) }}"
    description: "{{ inventory.description | default(default_description, true) }}"
    variables: "{{ inventory.variables | default(default_variables, true) }}"
    state: "{{ inventory.state | default(omit, true) }}"

- name: Create Host
  tower_host:
    tower_host: "{{ tower.host | default(default_tower_host, true) }}"
    tower_password: "{{ tower.password | default(default_tower_password, true) }}"
    tower_username: "{{ tower.username | default(default_tower_username, true) }}"
    name: "{{ host.name }}"
    inventory: "{{ inventory.name | default(default_inventory) }}"
    description: "{{ host.description | default(default_host_description) }}"
    variables: "{{ host.variables }}"
    state: "{{ host.state | default(omit) }}"
  loop: "{{ hosts | default([]) }}"
  loop_control:
    loop_var: host

- name: Create Group
  tower_group:
    tower_host: "{{ tower.host | default(default_tower_host, true) }}"
    tower_password: "{{ tower.password | default(default_tower_password, true) }}"
    tower_username: "{{ tower.username | default(default_tower_username, true) }}"
    inventory: "{{ inventory.name | default(default_inventory) }}"
    name: "{{ group.name }}"
    description: "{{ group.description | default(default_group_description) }}"
    variables: "{{ group.variables }}"
    state: "{{ group.state | default(omit) }}"
  loop: "{{ inventory.groups | default([]) }}"
  loop_control:
    loop_var: group